"""удалены поля из users

Revision ID: 14e8ded3a5dc
Revises: 6bf3b2d4dc1e
Create Date: 2025-05-02 17:11:08.700744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14e8ded3a5dc'
down_revision: Union[str, None] = '6bf3b2d4dc1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'age')
    op.drop_column('users', 'second_name')
    op.drop_column('users', 'speciality')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('speciality', sa.VARCHAR(), nullable=True))
    op.add_column('users', sa.Column('second_name', sa.VARCHAR(), nullable=True))
    op.add_column('users', sa.Column('age', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
