"""удалена таблица menu_table

Revision ID: 40153099f88f
Revises: 89abb4d0c77f
Create Date: 2025-05-02 19:06:50.355002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40153099f88f'
down_revision: Union[str, None] = '89abb4d0c77f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('menu_table')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu_table',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('id_weekday', sa.INTEGER(), nullable=False),
    sa.Column('id_dish', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['id_dish'], ['dishes.id'], ),
    sa.ForeignKeyConstraint(['id_weekday'], ['weekday.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
