"""добавили столбец в menu_table

Revision ID: 6bf3b2d4dc1e
Revises: 0c11c6d466fd
Create Date: 2025-04-21 17:15:32.676475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bf3b2d4dc1e'
down_revision: Union[str, None] = '0c11c6d466fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_table', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu_table', 'id')
    # ### end Alembic commands ###
