"""изменены таблицы столовой

Revision ID: 89abb4d0c77f
Revises: 14e8ded3a5dc
Create Date: 2025-05-02 18:43:47.826633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89abb4d0c77f'
down_revision: Union[str, None] = '14e8ded3a5dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dish_to_weekday',
    sa.Column('dishes', sa.Integer(), nullable=True),
    sa.Column('weekday', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dishes'], ['dishes.id'], ),
    sa.ForeignKeyConstraint(['weekday'], ['weekday.id'], )
    )
    op.add_column('dishes', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dishes', 'description')
    op.drop_table('dish_to_weekday')
    # ### end Alembic commands ###
